version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: lb_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: load_test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - lb_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lb_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://app:app@lb_postgres:5432/load_test
      - PORT=8080
    depends_on:
      - postgres
    networks:
      - lb_network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lb_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - lb_network
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  prometheus:
    image: prom/prometheus:latest
    container_name: lb_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitor/:/etc/prometheus/
    networks:
      - lb_network

  grafana:
    image: grafana/grafana:latest
    container_name: lb_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - lb_network
    volumes:
      - grafana_data:/var/lib/grafana

  k6:
    image: grafana/k6
    container_name: lb_k6
    tty: true
    networks:
      - lb_network
    volumes:
      - ./load-tester:/scripts

volumes:
  db_data:
  grafana_data:

networks:
  lb_network:
    driver: bridge