global:
  scrape_interval: 5s    # частота снятия метрик
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['lb_backend:8080']  # обращаемся к контейнеру backend по имени
